### ISSUE TITLE
transfer chunks of data

### ISSUE THREAD

**Issue by MaBecker** [noopkat/oled-js#114]
Hi,

have you thought about transfer chunks of data instead of bytes  for a full screen update ?

https://github.com/noopkat/oled-js/blob/master/oled.js#L398

What do you think ?

**Comment by MaBecker** [comment]
I expect this to be much faster as updating dirty bytes

**Comment by MaBecker** [comment]
https://github.com/MaBecker/oled-i2c-bus/commit/c099f6145024ea9b7c190d16a936eba45232e2a8

**Comment by noopkat** [comment]
@MaBecker hi! Thanks for the suggestion. Would you mind explaining this technique in a bit more detail, and how it differs to [this here](https://github.com/noopkat/oled-js/blob/master/oled.js#L530-L539), which finds the smallest chunk area to update (so that the 7 byte header is only sent once overall)? 

I'm sure it's faster as you're telling me it is, I'm just not quite grokking the concept from the code alone. Thanks! 😁

**Comment by noopkat** [comment]
@MaBecker it looks like perhaps it saves on the repetitive firmata I2C calls? That's my best understanding, it's been a while since I wrote this library hehe

**Comment by MaBecker** [comment]
Hi @noopkat,

sure - let me try ;-)

so first of all I use all call with sync = false to avoid   this._updateDirtyBytes(this.dirtyBytes);

because this does a byte by byte update of all the changes in buffer.

**The big thing is to send the complete buffer with 8 calls of 128 bytes to the oled and not with 1024 calls of 1 byte.** 

So a total update is even fast as a update of dirty bytes.

please let me know if you need more information.

**Comment by normen** [comment]
Hi, I did this in my fork of a fork of this library and it's indeed MUCH faster. I was using the C++ library to access the display before and was a bit shocked by how slow the JS library was so I investigated.

https://github.com/normen/oled_ssd1306_i2c

**Comment by noopkat** [comment]
that's so interesting! I have always tested this library with an Arduino Micro also 🤔  What is the largest chunk size you're able to successfully send using my version of this library rather than any forks (if you just quickly change the chunk size in my source)?

**Comment by normen** [comment]
Sorry, the fork I am using is running on RasPi completely, using the i2c library to access the displays via the RasPis GPIOs so I can't test your code. However, the C library I am using for Arduino and RasPi seems to send 16 bytes per package:
https://github.com/normen/ArduiPi_OLED/blob/4119148b051a6975816de2319eb6d11f6769499d/ArduiPi_OLED.cpp#L943

With my modified version for your JS library on RasPi-I2C I can send 32 bytes per package at 600kHz without issues. With the C library I do get the occasional hiccup when writing a lot at 600kHz - it does seem to push the data yet a bit faster for some reason. But with that I already get pretty much fluent animations at 100kHz.

**Comment by noopkat** [comment]
ah! I see. Yes this is definitely not an apples to apples comparison. This library was originally designed for Johnny-Five specifically which uses Firmata protocol. Firmata running on the board is probably the main bottleneck when using my library (it's almost the full 32kb in size), and combined with the emulated USB connection there's going to be issues. This is why I was super conservative after noticing problems with chunk size initially 😄

**Comment by normen** [comment]
I was just wondering because you seem to have a reason to pin the issue to the data transfer to the OLED - and I saw these little things handle more data that I expected. In my experience data transfer issues are hardware issues more often than not so maybe a few caps around the data transfer lines could make the appropriate bug fix? :)

**Comment by normen** [comment]
Alright, I see. My impression was mainly coming from how the JS code for the OLED is laid out - the error check and always sending one byte at a time. That looked like there was issues being solved in the past :) As said I am using a fork of your code and have really no idea of this johnny-five related setup. So my perspective is pretty much solely the JS code and while I was looking into getting this change in as far upstream as possible I found this issue.

So yeah, broadening my view to all of that I suppose your problem could be anything ;P

**Comment by noopkat** [comment]
thanks for getting in touch about it all the same. I'll consider implementing the dynamic chunk size option in the API but as far as my tests go not many will be able to make use of this feature given the nature of how this is integrated.
