### ISSUE TITLE
`opts` need to be passed through to i2cConfig

### ISSUE THREAD

**Issue by rwaldron** [noopkat/oled-js#123]
Here: https://github.com/noopkat/oled-js/blob/master/oled.js#L103 should be: 

```js
this._setUpI2C(opts);
```

And here: https://github.com/noopkat/oled-js/blob/master/oled.js#L158-L160 should be:

```js
Oled.prototype._setUpI2C = function(opts) {
  // enable i2C in firmata
  this.board.io.i2cConfig(opts);
```

Otherwise non-firmata io-plugins are unable to send special properties along to `i2cConfig`, which results in bugs like this: https://github.com/rwaldron/tessel-io/issues/18

**Comment by noopkat** [comment]
makes sense! I can fix this

**Comment by rwaldron** [comment]
Thanks ❤️

**Comment by opkiler22789** [comment]
@noopkat  looking forward to it

**Comment by noopkat** [comment]
closing this as the fix has been published. Thank you for your help, @rwaldron 💯 
![bitmoji](https://render.bitstrips.com/v2/cpanel/9941956-209725411_1-s4-v1.png?transparent=1&palette=1&width=246)
