### ISSUE TITLE
use .npmignore to cut down package size

### ISSUE THREAD

**Issue by noopkat** [noopkat/oled-js#133]
we could be creating much smaller taballs on publish if we npmignored:

+ fritzing breadboard files
+ tests (?)
+ images (most of them are used in tests)

**Comment by Lisiadito** [comment]
I think instead of using `.npmignore` for blacklisting, the better way would be to use the `files` property in the `package.json` to whitelist the file you want to publish. Which is basically only the `oled.js` right? 
I would open a PR for that if you agree @noopkat ?!

**Comment by noopkat** [comment]
@Lisiadito sure thing I'd really appreciate that, go right ahead 😄

**Comment by noopkat** [comment]
closed by #134
