### ISSUE TITLE
diagonal scroll methods do not work

### ISSUE THREAD

**Issue by noopkat** [noopkat/oled-js#17]

**Comment by Traverso** [comment]
Added af fix in my latest pull request

**Comment by noopkat** [comment]
Hi :)
I can't see a new PR open, am I missing something?

**Comment by Traverso** [comment]
Nope, my bad - I'm still not 100% on the GitHub client.

**Comment by noopkat** [comment]
thank you! I'll look at it when I get a moment 👍

**Comment by noopkat** [comment]
I just published your fix in 3.1.2 - thank you! Sorry for the long delay again 😭
